apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-pvc
  namespace: moodle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
